name: domino_pub_exp
description: Domino experiments for pub-dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  domino: ^0.6.0
  async_tracker: ^0.1.2

dev_dependencies:
  domino_generator:
    path: ../domino_generator
  pedantic: ^1.11.0

dependency_overrides:
  domino:
    path: ../domino
