name: domino
description: An experimental virtual dom library, which allows mixing DOM elements with components.
version: 0.6.0
homepage: https://github.com/domino-dart/domino/tree/master/domino

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  async_tracker: ^0.1.1
  meta: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.3.0
