name: domino_generator
description: Code generator for HTML/JS widgets using package:domino.
version: 0.6.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dart_style: ^1.3.3
  domino:
    path: ../domino
  html: ^0.14.0
  meta: ^1.0.0

dev_dependencies:
  pedantic: 1.8.0
  test: ^1.0.0
