name: domino_generator
description: Code generator for HTML/JS widgets using package:domino.
version: 0.7.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  code_builder: ^4.0.0
  crypto: ^3.0.1
  dart_style: ^2.0.0
  domino: ^0.7.0
  html: ^0.15.0
  meta: ^1.3.0
  path: ^1.8.0
  xml: ^5.1.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

executables:
  domino_generator:

dependency_overrides:
  domino:
    path: domino
