name: domino_generator
description: Code generator for HTML/JS widgets using package:domino.
version: 0.6.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  crypto: ^2.0.0
  dart_style: ^1.3.3
  domino: ^0.6.0
  html: ^0.14.0
  meta: ^1.0.0
  path: ^1.0.0
  xml: ^4.1.0

dev_dependencies:
  pedantic: 1.8.0
  test: ^1.0.0

executables:
  domino_generator:

dependency_overrides:
  domino:
    path: ../domino
