name: domino_web_example
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  domino: ^0.6.0
  async_tracker: ^0.1.2
#  path: ^1.6.0

dev_dependencies:
  domino_generator:
    path: ../domino_generator
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  pedantic: ^1.8.0

dependency_overrides:
  domino:
    path: ../domino
